version: '3.7'
services:
  currency-exchange:
    image: shahintraining/currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8234:8234"
    networks:
      - currency-network
    depends_on :
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: ampq://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKING_SENDER_TYPE: rabbit
  
  currency-conversion:
    image: shahintraining/currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"    
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
        SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
        RABBIT_URI: ampq://guest:guest@rabbitmq:5672
        SPRING_RABBITMQ_HOST: rabbitmq
        SPRING_ZIPKING_SENDER_TYPE: rabbit
  
  api-gateway:
    image: shahintraining/api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"    
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
        SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
        RABBIT_URI: ampq://guest:guest@rabbitmq:5672
        SPRING_RABBITMQ_HOST: rabbitmq
        SPRING_ZIPKING_SENDER_TYPE: rabbit


  naming-server:
    image: shahintraining/naming-server:0.0.1-SNAPSHOT
    mem_limit : 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin
    mem_limit : 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    depends_on :
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.9.7-management
    mem_limit : 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-network

networks:
  currency-network: